[Fix] Add delay for pending operations to complete
gluster/glusterfs-containers-tests pull request #53
Opened 2021-08-02 13:01 UTC by SushilG96

Signed-off-by: SushilG96 <susgupta@redhat.com>

2021-08-03 07:44 UTC, vamahaja requested changes

2021-08-03 07:44 UTC, vamahaja commented on tests/functional/heketi/test_volume_deletion.py
> +        for w in waiter.Waiter(timeout=240, interval=10):
Change this to `timeout=300, interval=15`

2021-08-04 05:33 UTC, vamahaja approved these changes

2021-08-04 05:36 UTC, srivickynesh approved these changes
LGTM

2021-08-04 05:36 UTC, merged